Add New Methods to help with system orchestration
utopia-php/system pull request #16
Opened 2022-05-17 12:57 UTC by PineappleIOnic

+ Added getCPUCores()
+ Added UNIX Helper functions
+ Added getCPUUtilisation
+ Added getMemoryTotal()
+ Added getMemoryFree()
+ Added getDiskTotal()
+ Added getDiskFree()
+ Added getDiskStats()
+ Added getIOUsage()
+ Added getNetworkUsage()

Most of these methods are currently Linux only and are currently being iterated on to improve stability.

2022-05-17 14:47 UTC, wess commented on src/System/System.php
> +            return preg_replace('/\s+/', ' ', trim($data));
no need for \t?

2022-05-20 07:06 UTC, eldadfux commented
@PineappleIOnic lets add a lot of tests :)

2022-06-21 12:42 UTC, Meldiron commented on src/System/System.php
> +            sleep(1);
Same as comment above, can we make this attribute?

2022-06-21 15:47 UTC, PineappleIOnic commented on tests/System/SystemTest.php
> +        $this->assertIsInt(System::getCPUCores());
Unfortunately, this isn't possible as docker does not write the container's information into the kernel files we read but instead writes the host's usage.

2022-07-06 09:05 UTC, eldadfux requested changes

2022-07-06 09:05 UTC, eldadfux commented on src/System/System.php
> +            $data[$cpuNumber]['guest'] = isset($cpu[9]) ? $cpu[9] : 0;
We can use the null safety check and give proper default where needed.

2022-07-06 09:05 UTC, eldadfux commented on src/System/System.php
> +                throw new Exception(self::getOS() . " not supported.");
Would be nice to add a table covering all the different method that are not supported in all operating systems.

2022-07-06 09:05 UTC, eldadfux commented on src/System/System.php
> +                return intval($matches[1] / 1024);
Accessing the array key directly without validating it exists is risky. Let's have a null safety check.

2022-07-06 09:05 UTC, eldadfux commented on src/System/System.php
> +                if (str_contains($disk[2], $filter)) {
Same about null safety. Lets make sure we take care of it across the library.

2022-08-06 06:58 UTC, eldadfux commented
Tests are failing.

2022-08-08 09:13 UTC, PineappleIOnic commented
The tests failing appear to be a Travis issue as they complain about an argon2 dependency; all other tests are passing

2022-09-23 13:24 UTC, eldadfux approved these changes

2022-09-23 13:24 UTC, merged