added code analyzer
utopia-php/system pull request #22
Opened 2022-10-23 14:58 UTC by DevMike123

Continuation of #19 . Uses Level 6 composer. All errors fixed. @Meldiron pr ready for merge.
![success](https://user-images.githubusercontent.com/80250971/197399302-8831f705-c139-4d2f-852a-316854e6ca4f.PNG)

2022-10-31 16:10 UTC, DevMike123 commented
@Steven can you review the pr?

2022-10-31 16:11 UTC, DevMike123 commented
@stnguyen90 can you review the pr?

2022-10-31 16:26 UTC, PineappleIOnic commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-07 20:12 UTC, stnguyen90 commented
@DevMike123 looks like there are merge conflicts. Would you please resolve them?

2022-11-08 03:49 UTC, DevMike123 commented
> @DevMike123 looks like there are merge conflicts. Would you please resolve them?

@stnguyen90 done.

2022-11-08 19:26 UTC, stnguyen90 requested changes
Great PR! 🤯 We left some comments during the review, please check them out.

2022-11-08 19:26 UTC, stnguyen90 commented on composer.json
> +"phpstan/phpstan": "1.9.x-dev"
The formatting of this JSON is a little off. Would you please fix it?

2022-11-08 19:26 UTC, stnguyen90 commented on src/System/System.php
> +                {preg_match_all('/^processor/m', $cpuinfo, $matches);
This doesn't match our code style. Please use `composer format` to ensure it matches our style.

2022-11-08 19:26 UTC, stnguyen90 commented on composer.json
> +        "check": "./vendor/bin/phpstan analyse --level 6 src tests",
level 8 only adds 2 more errors that need to be fixed. Would you be able to change to 8 and fix those errors?

2022-11-09 10:20 UTC, closed without merging