upgraded issue template to issue forms
utopia-php/system pull request #9
Opened 2021-10-01 13:01 UTC by vj-codes

Fixes #8

2021-10-01 14:41 UTC, lohanidamodar requested changes
Hey, we have few more changes required. For example you can ask for the library version, php version and code of conduct on all the templates. We have a first approved PR please take that as reference
https://github.com/utopia-php/framework/pull/28

2021-10-01 18:47 UTC, vj-codes commented
@lohanidamodar done, please review again
Thankss in advance:)

2021-10-03 06:25 UTC, lohanidamodar commented
@vj-codes it seems the form has some errors. Please correct those. Make sure to test it on your repository.
![image](https://user-images.githubusercontent.com/6360216/135742641-a577cc08-c65f-47bf-9138-791956c5dc91.png)

2021-10-05 18:56 UTC, vj-codes commented
@lohanidamodar done!

2021-10-30 08:19 UTC, Meldiron requested changes
Requested 2 tiny changes

2021-10-30 08:19 UTC, Meldiron commented on .github/ISSUE_TEMPLATE/feature.yaml
> +        Thanks for taking the time to fill out our bug report form 🙏
Please update this part as showed in our template. We cannot thank for bug report in feature request.

2021-10-30 08:19 UTC, Meldiron commented on .github/ISSUE_TEMPLATE/documentation.yaml
> +        Thanks for taking the time to fill out our bug report form 🙏
Please update this part as showed in our template. We cannot thank for bug report in documentation update.

2021-11-28 09:59 UTC, christyjacob4 commented
@vj-codes  closing this PR for now since there has been no activity in quite a long time. Feel free to reopen it when you're ready to start working on it once again.

2021-11-28 09:59 UTC, closed without merging